# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/exynos4tab-common/extract-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/samsung/exynos4tab-common/proprietary/audio/lib/libmediayamahaservice.so:obj/lib/libmediayamahaservice.so \
    vendor/samsung/exynos4tab-common/proprietary/hwcomposer/lib/libTVOut.so:obj/lib/libTVOut.so \
    vendor/samsung/exynos4tab-common/proprietary/hwcomposer/lib/libfimc.so:obj/lib/libfimc.so

# AUDIO
PRODUCT_COPY_FILES += \
    vendor/samsung/exynos4tab-common/proprietary/audio/lib/hw/alsa.default.so:system/lib/hw/alsa.default.so \
    vendor/samsung/exynos4tab-common/proprietary/audio/lib/hw/audio.a2dp.default.so:system/lib/hw/audio.a2dp.default.so \
    vendor/samsung/exynos4tab-common/proprietary/audio/lib/hw/audio.primary.exynos4.so:system/lib/hw/audio.primary.exynos4.so \
    vendor/samsung/exynos4tab-common/proprietary/audio/lib/hw/audio_policy.exynos4.so:system/lib/hw/audio_policy.exynos4.so \
    vendor/samsung/exynos4tab-common/proprietary/audio/lib/lib_Samsung_Acoustic_Module_Llite.so:system/lib/lib_Samsung_Acoustic_Module_Llite.so \
    vendor/samsung/exynos4tab-common/proprietary/audio/lib/lib_Samsung_Resampler.so:system/lib/lib_Samsung_Resampler.so \
    vendor/samsung/exynos4tab-common/proprietary/audio/lib/lib_Samsung_Sound_Booster.so:system/lib/lib_Samsung_Sound_Booster.so \
    vendor/samsung/exynos4tab-common/proprietary/audio/lib/libasound.so:system/lib/libasound.so \
    vendor/samsung/exynos4tab-common/proprietary/audio/lib/liblvvefs.so:system/lib/liblvvefs.so \
    vendor/samsung/exynos4tab-common/proprietary/audio/lib/libmediayamaha.so:system/lib/libmediayamaha.so \
    vendor/samsung/exynos4tab-common/proprietary/audio/lib/libmediayamaha_jni.so:system/lib/libmediayamaha_jni.so \
    vendor/samsung/exynos4tab-common/proprietary/audio/lib/libmediayamaha_tuning_jni.so:system/lib/libmediayamaha_tuning_jni.so \
    vendor/samsung/exynos4tab-common/proprietary/audio/lib/libmediayamahaservice.so:system/lib/libmediayamahaservice.so \
    vendor/samsung/exynos4tab-common/proprietary/audio/lib/libsamsungAcousticeq.so:system/lib/libsamsungAcousticeq.so \
    vendor/samsung/exynos4tab-common/proprietary/audio/lib/libsamsungSoundbooster.so:system/lib/libsamsungSoundbooster.so \
    vendor/samsung/exynos4tab-common/proprietary/audio/lib/libyamahasrc.so:system/lib/libyamahasrc.so \
	vendor/samsung/exynos4tab-common/proprietary/audio/lib/libbt-aptx-4.0.3.so:system/lib/libbt-aptx-4.0.3.so

# EGL
PRODUCT_COPY_FILES += \
    vendor/samsung/exynos4tab-common/proprietary/graphics/lib/hw/gralloc.exynos4.so:system/lib/hw/gralloc.exynos4.so \
    vendor/samsung/exynos4tab-common/proprietary/graphics/lib/egl/libEGL_mali.so:system/lib/egl/libEGL_mali.so \
    vendor/samsung/exynos4tab-common/proprietary/graphics/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
    vendor/samsung/exynos4tab-common/proprietary/graphics/lib/egl/libGLESv1_CM_mali.so:system/lib/egl/libGLESv1_CM_mali.so \
    vendor/samsung/exynos4tab-common/proprietary/graphics/lib/egl/libGLESv2_mali.so:system/lib/egl/libGLESv2_mali.so \
    vendor/samsung/exynos4tab-common/proprietary/graphics/lib/libGLESv1_CM.so:system/lib/libGLESv1_CM.so \
    vendor/samsung/exynos4tab-common/proprietary/graphics/lib/libGLESv2.so:system/lib/libGLESv2.so \
    vendor/samsung/exynos4tab-common/proprietary/graphics/lib/libGLESv2_dbg.so:system/lib/libGLESv2_dbg.so \
    vendor/samsung/exynos4tab-common/proprietary/graphics/lib/libion.so:system/lib/libion.so \
    vendor/samsung/exynos4tab-common/proprietary/graphics/lib/libMali.so:system/lib/libMali.so \
    vendor/samsung/exynos4tab-common/proprietary/graphics/lib/libUMP.so:system/lib/libUMP.so

# HWCOMPOSER
PRODUCT_COPY_FILES += \
    vendor/samsung/exynos4tab-common/proprietary/hwcomposer/lib/hw/hwcomposer.exynos4.so:system/lib/hw/hwcomposer.exynos4.so \
    vendor/samsung/exynos4tab-common/proprietary/hwcomposer/bin/bintvoutservice:system/bin/bintvoutservice \
    vendor/samsung/exynos4tab-common/proprietary/hwcomposer/lib/libcec.so:system/lib/libcec.so \
    vendor/samsung/exynos4tab-common/proprietary/hwcomposer/lib/libddc.so:system/lib/libddc.so \
    vendor/samsung/exynos4tab-common/proprietary/hwcomposer/lib/libedid.so:system/lib/libedid.so \
    vendor/samsung/exynos4tab-common/proprietary/hwcomposer/lib/libfimc.so:system/lib/libfimc.so \
    vendor/samsung/exynos4tab-common/proprietary/hwcomposer/lib/libhdmi.so:system/lib/libhdmi.so \
    vendor/samsung/exynos4tab-common/proprietary/hwcomposer/lib/libhdmiclient.so:system/lib/libhdmiclient.so \
    vendor/samsung/exynos4tab-common/proprietary/hwcomposer/lib/libTVOut.so:system/lib/libTVOut.so \
    vendor/samsung/exynos4tab-common/proprietary/hwcomposer/lib/libtvout_jni.so:system/lib/libtvout_jni.so \
    vendor/samsung/exynos4tab-common/proprietary/hwcomposer/lib/libtvoutinterface.so:system/lib/libtvoutinterface.so \
    vendor/samsung/exynos4tab-common/proprietary/hwcomposer/lib/libtvoutservice.so:system/lib/libtvoutservice.so

# SENSORS
PRODUCT_COPY_FILES += \
    vendor/samsung/exynos4tab-common/proprietary/sensors/lib/hw/sensors.exynos4.so:system/lib/hw/sensors.exynos4.so \
    vendor/samsung/exynos4tab-common/proprietary/sensors/lib/libakm.so:system/lib/libakm.so \
    vendor/samsung/exynos4tab-common/proprietary/sensors/lib/libmllite.so:system/lib/libmllite.so \
    vendor/samsung/exynos4tab-common/proprietary/sensors/lib/libmlplatform.so:system/lib/libmlplatform.so \
    vendor/samsung/exynos4tab-common/proprietary/sensors/lib/libmpl.so:system/lib/libmpl.so

# GPS
PRODUCT_COPY_FILES += \
    vendor/samsung/exynos4tab-common/proprietary/gps/lib/hw/gps.exynos4.so:system/lib/hw/gps.exynos4.so \
    vendor/samsung/exynos4tab-common/proprietary/gps/bin/gpsd:system/bin/gpsd \
    vendor/samsung/exynos4tab-common/proprietary/gps/bin/gps.cer:system/bin/gps.cer

# hwaccel firmware
PRODUCT_COPY_FILES += \
    vendor/samsung/exynos4tab-common/proprietary/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin
